/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author mattes
 */
public class Hauptfenster extends javax.swing.JFrame implements ActionListener
{

    
    private int kontonr[];
    private int gewaehltesKonto;
    
    /**
     * Creates new form Hauptfenster
     */
    public Hauptfenster() {
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edit_Profile = new javax.swing.JButton();
        change_accnr = new javax.swing.JComboBox<>();
        ueberweisung = new javax.swing.JButton();
        ueberweisungsvorlage = new javax.swing.JButton();
        kontoauszug = new javax.swing.JButton();
        kontolist = new javax.swing.JButton();
        scrollpane = new javax.swing.JScrollPane();
        intFrame = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        edit_Profile.setText("Profil bearbeiten");
        edit_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_ProfileActionPerformed(evt);
            }
        });

        change_accnr.setModel(getCBoxModel());
        change_accnr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                change_accnrItemStateChanged(evt);
            }
        });

        ueberweisung.setText("Überweisung");
        ueberweisung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ueberweisungActionPerformed(evt);
            }
        });

        ueberweisungsvorlage.setText("Überweisungsvorlage");
        ueberweisungsvorlage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ueberweisungsvorlageActionPerformed(evt);
            }
        });

        kontoauszug.setText("Kontoauszug");
        kontoauszug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontoauszugActionPerformed(evt);
            }
        });

        kontolist.setText("Kontoliste");
        kontolist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontolistActionPerformed(evt);
            }
        });

        intFrame.setVisible(true);
        intFrame.getContentPane().setLayout(new java.awt.GridLayout(0, 1));
        scrollpane.setViewportView(intFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kontolist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kontoauszug, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ueberweisungsvorlage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ueberweisung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edit_Profile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(change_accnr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_Profile)
                    .addComponent(change_accnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ueberweisung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ueberweisungsvorlage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kontoauszug)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kontolist)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollpane))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_ProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_ProfileActionPerformed

    private void ueberweisungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ueberweisungActionPerformed
        Container c=intFrame.getContentPane();
        c.removeAll();
        JPanel p=new JPanel();
        c.add(p);
        JButton b=new JButton("neue Überweisung");
        b.setActionCommand("neueUeberweisung");
        b.addActionListener(this);
        p.add(b);
        p=new JPanel();
        c.add(p);
        b=new JButton("Überweisung stornieren");
        b.setActionCommand("storno");
        b.addActionListener(this);
        p.add(b);
        scrollpane.paintAll(scrollpane.getGraphics());
    }//GEN-LAST:event_ueberweisungActionPerformed

    private void ueberweisungsvorlageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ueberweisungsvorlageActionPerformed
        JButton b=new JButton("Überweisungsvorlage bearbeiten");
        Container c=intFrame.getContentPane();
        b.setActionCommand("bearbeiteVorlage");
        b.addActionListener(this);
        c.removeAll();
        c.add(b);
        b=new JButton("neue Überweisungsvorlage");
        b.setActionCommand("neueVorlage");
        b.addActionListener(this);
        c.add(b);
        b=new JButton("Überweisungsvorlage löschen");
        b.setActionCommand("loeschVorlage");
        b.addActionListener(this);
        c.add(b);
        scrollpane.paintAll(scrollpane.getGraphics());
    }//GEN-LAST:event_ueberweisungsvorlageActionPerformed

    private void kontoauszugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontoauszugActionPerformed
        Container c=intFrame.getContentPane();
        c.removeAll();
        JPanel p=null;
        c.add(new JLabel("Kontoauszug fuer Konto "+gewaehltesKonto+":"));
        int lines=1;
        for(int i=0;i<lines;i++)
        {
            p=new JPanel();
            c.add(p);
            p.add(new JLabel("Testbetrag: 96€"));
        }
        scrollpane.paintAll(scrollpane.getGraphics());
    }//GEN-LAST:event_kontoauszugActionPerformed

    private void kontolistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontolistActionPerformed
        Container c=intFrame.getContentPane();
        c.removeAll();
        JPanel p=new JPanel();
        c.add(p);
        p.add(new JLabel("Kontoliste:"));
        for(int i=0;i<kontonr.length;i++)
        {
            p=new JPanel();
            c.add(p);
            p.add(new JLabel(""+kontonr[i]));
            p.add(new JLabel(""+"Betrag gesucht durch searchByID"));
        }
        scrollpane.paintAll(scrollpane.getGraphics());
    }//GEN-LAST:event_kontolistActionPerformed

    private void change_accnrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_change_accnrItemStateChanged
        try
        {
            gewaehltesKonto=Integer.parseInt(evt.getItem().toString());
        }
        catch(NumberFormatException nfe)
        {
            System.out.println("FEHLER: "+nfe.getMessage());
        }
    }//GEN-LAST:event_change_accnrItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hauptfenster().setVisible(true);
            }
        });
    }
    
    private ComboBoxModel getCBoxModel()
    {
        kontonr=new int[2];
        kontonr[0]=1234598;
        kontonr[1]=5401423;
        String Items[]=new String[kontonr.length];
        Items[0]=""+kontonr[0];
        Items[1]=""+kontonr[1];
        gewaehltesKonto=kontonr[0];
        return new DefaultComboBoxModel(Items);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> change_accnr;
    private javax.swing.JButton edit_Profile;
    private javax.swing.JInternalFrame intFrame;
    private javax.swing.JButton kontoauszug;
    private javax.swing.JButton kontolist;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JButton ueberweisung;
    private javax.swing.JButton ueberweisungsvorlage;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae)
    {
        switch (ae.getActionCommand())
        {
            case "neueUeberweisung":
                break;
            case "storno":
                break;
            case "bearbeiteVorlage":
                break;
            case "neueVorlage":
                break;
            case "loeschVorlage":
                break;
            default:
                break;
        }
    }

}
